server:
  port: 8000

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mall-cms
          uri: lb://mall-cms
          predicates:
            - Path=/mall_cms/**
          filters:
            - StripPrefix=1

        - id: mall-goods
          uri: lb://mall-goods
          predicates:
            - Path=/mall_goods/**
          filters:
            - StripPrefix=1

        - id: mall-goods-search
          uri: lb://mall-goods-search
          predicates:
            - Path=/mall_goods_search/**
          filters:
            - StripPrefix=1
