server:
  port: 8002

spring:
  application:
    name: mall-auth

  cloud:
    nacos:
      discovery:
        server-addr: 114.116.105.15:8848


  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://114.116.105.15:3306/lilishop?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    host: 114.116.105.15
    port: 6379

mybatis-plus:
  type-aliases-package: com.rainbow.mall.auth.pojo.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


mall:
  swagger:
    enable: true
    basePackage: com.rainbow.mall.goods.controller
    title: mall-goods
    description: mall商品模块接口文档
    contact: melo-lh
    version: 1.0


security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8002/user

logging:
  level:
    com.rainbow.mall.goods.service.mapper: debug