server:
  port: 9001

spring:
  application:
    name: raimbow-mall-cms

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lilishop?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  type-aliases-package: com.rainbow.mall.cms.pojo.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mall:
  swagger:
    enable: true
    basePackage: com.rainbow.mall.cms.controller
    title: mall-cms
    description: mall内容管理测试文档
    contact: melo-lh
    version: 1.0